#!/bin/sh

set -e

orig_dir="$(pwd)"

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

project_dir="$(pwd)"

local_script="$project_dir/../benchdiff/script/benchdiff"
if [ -f "$local_script" ]; then
    cd "$orig_dir"
    exec "$local_script" "$@"
fi

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

script/bindown install benchdiff > /dev/null
cd "$orig_dir"

exec "$project_dir/bin/benchdiff" "$@"
