name: bench

on:
  push:

jobs:
  bench:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.10"
      - uses: ./.github/actions/benchdiff
        id: benchdiff
        with:
          benchdiff_version: 0.3.0
          benchdiff_args: --base-ref=$default_base_ref --bench-count=5 --benchtime 10ms --on-degrade 3
      - name: output
        run: |
          echo benchdiff_out:
          echo '${{ steps.benchdiff.outputs.benchdiff_out }}'
          echo benchstat_out:
          echo '${{ steps.benchdiff.outputs.benchstat_out }}'
      - name: report status
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |

          output_summary='
          \`\`\`
          ${{ steps.benchdiff.outputs.benchdiff_out }}
          \`\`\`
          '

          conclusion="success"
          head_sha="$(git rev-parse HEAD)"
          name="benchdiff result"
          output_title=""

          postdata="$(jq -n \
          --arg conclusion "$conclusion" \
          --arg head_sha "$head_sha" \
          --arg name "$name" \
          --arg output_summary "$output_summary" \
          --arg output_title "$output_title" \
          '
            {
              "conclusion": $conclusion,
              "head_sha": $head_sha,
              "name": $name,
              "output": {
                "summary": $output_summary,
                "title": $output_title
              }
            }
          '
          )"

          curl -X 'POST' -d "$postdata" \
          -H 'Accept: application/vnd.github.v3+json, application/vnd.github.antiope-preview+json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: token $GITHUB_TOKEN" \
          'https://api.github.com/repos/WillAbides/bench-test/check-runs'
