name: bench

on:
  push:

jobs:
  bench:
    runs-on: ubuntu-20.04
    env:
      benchdiff_version: "0.1.1"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/benchdiff
        id: benchdiff
        with:
          benchdiff_version: 0.2.0
          benchdiff_args: --base-ref=$default_base_ref --degradation-exit 3
      - name: output
        run: echo "${{ steps.benchdiff.outputs.benchdiff_out }}"
