name: bench

on:
  push:

jobs:
  statuscheck:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: status
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          status_name="statuscheck-result"
          commit_sha="$(git rev-parse HEAD)"
          posttmpl='{"conclusion":"%s","head_sha":"%s","name":"%s","output":{"summary":"","text":"some summary text","title":"my output"}}'
          postdata="$(printf "$posttmpl" "neutral" "$commit_sha" "$status_name")"
          curl -X 'POST' -d "$postdata" \
          -H 'Accept: application/vnd.github.v3+json, application/vnd.github.antiope-preview+json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: token $GITHUB_TOKEN" \
          'https://api.github.com/repos/WillAbides/bench-test/check-runs'
  bench:
    if: ${{ false }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/benchdiff
        id: benchdiff
        with:
          benchdiff_version: 0.2.0
          benchdiff_args: --base-ref=$default_base_ref --bench-count=1 --degradation-exit 3
      - name: output
        run: echo "${{ steps.benchdiff.outputs.benchdiff_out }}"
