name: bench

on:
  push:
  workflow_dispatch:

jobs:
  benchdiff:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.15"
      - uses: WillAbides/benchdiff-action@debug
        id: benchdiff
        with:
          benchdiff_version: 0.5.6
          benchdiff_args: --base-ref=$default_base_ref --count=5 --benchtime 10ms --benchstat-output markdown
      - name: output
        run: |
          echo benchstat_output:
          echo '${{ steps.benchdiff.outputs.benchstat_output }}'
          echo bench_command:
          echo '${{ steps.benchdiff.outputs.bench_command }}'
          echo head_sha:
          echo '${{ steps.benchdiff.outputs.head_sha }}'
          echo base_sha:
          echo '${{ steps.benchdiff.outputs.base_sha }}'
          echo degraded_result:
          echo '${{ steps.benchdiff.outputs.degraded_result }}'
