name: crypto-bench

on:
  push:
    branches:
      - cryptobench
  workflow_dispatch:

jobs:
  crypto-bench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: golang/crypto
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.15"
      - uses: WillAbides/benchdiff-action@v0
        id: benchdiff
        with:
          benchdiff_version: 0.5.7
          status_sha: ${{ github.sha }}
          status_name: crypto-bench-result
          benchdiff_args: |
            --cpu=1,2 --warmup-count=1 --warmup-time=10ms --count=1 --benchtime 10ms --tolerance=50 --packages='./argon2/...' --debug
